Repository CanCanCommunity/cancancan, pull requests merged in 2020-12, with the labels that each got.

#650 Feature/536 investigate association rule issue
  lib/cancan/conditions_matcher.rb
  spec/cancan/model_adapters/active_record_adapter_spec.rb
Labels: waiting for feedback

#657 Remove unnecessary call to `resolve_column_aliases`
  .travis.yml
  Appraisals
  gemfiles/activerecord_master.gemfile
  lib/cancan/model_adapters/active_record_5_adapter.rb
Labels: next minor release

#655 Add option for `accessible_by` querying strategy
  CHANGELOG.md
  lib/cancan.rb
  lib/cancan/config.rb
  lib/cancan/model_adapters/active_record_4_adapter.rb
  lib/cancan/model_adapters/active_record_5_adapter.rb
  lib/cancan/model_adapters/active_record_adapter.rb
  spec/cancan/model_adapters/accessible_by_has_many_through_spec.rb
  spec/cancan/model_adapters/active_record_4_adapter_spec.rb
  spec/cancan/model_adapters/active_record_5_adapter_spec.rb
  spec/cancan/model_adapters/active_record_adapter_spec.rb
  spec/cancan/model_adapters/has_and_belongs_to_many_spec.rb
  spec/spec_helper.rb
  spec/support/sql_helpers.rb
Labels: waiting for feedback

#669 Switch to github actions
  .github/workflows/test.yml
  Appraisals
  gemfiles/activerecord_6.1.0.gemfile
  gemfiles/activerecord_master.gemfile
  spec/support/sql_helpers.rb
Labels: enhancement, waiting for feedback
